"""Compatibility exports for cross-service contract tests.

Production service code should use service-local models.
"""

from services.query_generator_agent.app.models import (
    PromptFetchRequest,
    PromptSnapshotResponse,
    QAQuestionRequest,
    QueryGeneratorRepairReceipt,
    QueryQuestionResponse,
    RepairAction,
    RepairPlan,
    RepairPlanEnvelope,
)
from services.repair_agent.app.models import (
    KRSSAnalysisRecord,
    KRSSIssueTicketResponse,
    KnowledgeRepairSuggestionRequest,
    KnowledgeType,
)
from services.testing_agent.app.models import (
    ActualAnswer,
    CypherGenerationRequest,
    Difficulty,
    DimensionStatus,
    DispatchStatus,
    EvaluationDimensions,
    EvaluationState,
    EvaluationSubmissionRequest,
    EvaluationSubmissionResponse,
    EvaluationSummary,
    ExpectedAnswer,
    GeneratedCypher,
    GenerationContext,
    GenerationProcessingStatus,
    ImprovementAssessment,
    ImprovementDimensions,
    ImprovementDimensionStatus,
    ImprovementStatus,
    IssueTicket,
    KnowledgeContext,
    KnowledgePackage,
    QAGoldenRequest,
    QAGoldenResponse,
    RepairPlanState,
    RootCauseType,
    TuGraphExecutionResult,
    Verdict,
)

__all__ = [
    "ActualAnswer",
    "CypherGenerationRequest",
    "Difficulty",
    "DimensionStatus",
    "DispatchStatus",
    "EvaluationDimensions",
    "EvaluationState",
    "EvaluationSubmissionRequest",
    "EvaluationSubmissionResponse",
    "EvaluationSummary",
    "ExpectedAnswer",
    "GeneratedCypher",
    "GenerationContext",
    "GenerationProcessingStatus",
    "ImprovementAssessment",
    "ImprovementDimensionStatus",
    "ImprovementDimensions",
    "ImprovementStatus",
    "IssueTicket",
    "KRSSAnalysisRecord",
    "KRSSIssueTicketResponse",
    "KnowledgeContext",
    "KnowledgePackage",
    "KnowledgeRepairSuggestionRequest",
    "KnowledgeType",
    "PromptFetchRequest",
    "PromptSnapshotResponse",
    "QAGoldenRequest",
    "QAGoldenResponse",
    "QAQuestionRequest",
    "QueryGeneratorRepairReceipt",
    "QueryQuestionResponse",
    "RepairAction",
    "RepairPlan",
    "RepairPlanEnvelope",
    "RepairPlanState",
    "RootCauseType",
    "TuGraphExecutionResult",
    "Verdict",
]
