#!/usr/bin/env bash

SOURCE_ROOT_NL2CYPHER="/Users/mangowmac/Desktop/code/NL2Cypher"
SOURCE_CYPHER_GENERATOR="${SOURCE_ROOT_NL2CYPHER}/services/cypher_generator_agent"
SOURCE_TESTING="${SOURCE_ROOT_NL2CYPHER}/services/testing_agent"
SOURCE_REPAIR="${SOURCE_ROOT_NL2CYPHER}/services/repair_agent"
SOURCE_CONSOLE="${SOURCE_ROOT_NL2CYPHER}/console/runtime_console"
SOURCE_CONTRACTS="${SOURCE_ROOT_NL2CYPHER}/contracts"

SOURCE_KNOWLEDGE="${SOURCE_ROOT_NL2CYPHER}/third_party/knowledge-agent"
SOURCE_QA="${SOURCE_ROOT_NL2CYPHER}/third_party/qa-agent"
